<?php

namespace App\Services;

use App\Models\Authgroup;


/**
 * 权限分组管理
 * Class AuthgroupService
 * @package App\Services
 */
class AuthgroupService extends BaseService
{
    /**
     * 构造方法
     * @author zongjl
     * @date 2019/5/23
     */
    public function __construct()
    {
        $this->setModel(new Authgroup());
    }

    public function getList()
    {
        return parent::getList([], [['id', 'asc']]); // TODO: Change the autogenerated stub
    }

    /**
     * 获取分组列表
     * @param bool $isKeyVal
     * @return mixed
     */
    public function getSelectList($isKeyVal = false)
    {
        $result = $this->model->getSelectList();
        if ($isKeyVal && $result) {
            $result=collect($result);
            $result=$result->keyBy('id');
            $result= $result->all();
        }
        return $result;
    }
}
