<?php

namespace App\Services;

use App\Models\DictType;
use App\Validates\DictTypeValidate;


/**
 * 字典分类
 * Class DictTypeService
 * @package App\Services
 */
class DictTypeService extends BaseService
{
    /**
     * 构造方法
     */
    public function __construct()
    {
        $this->setModel(new DictType());
        $this->setValidate(new DictTypeValidate());
    }

    public function getTypeList(){
        return $this->model->getList([],['type','name'],[],'',[['listsort','asc']]);
    }

    public function drop()
    {
        return parent::drop([],'type'); // TODO: Change the autogenerated stub
    }

    public function after_drop($data)
    {
        (new DictDataService())->drop($data,'type');
        return parent::after_drop($data); // TODO: Change the autogenerated stub
    }
}
