<?php

namespace App\Validates;


use App\Services\AdpositionService;

class AdpositionValidate extends ValidateBase
{
    public function rules()
    {
        return [
            'title' => 'required|min:2|max:50',
            'type' => 'required|min:3|max:50|alpha_dash'
        ];
    }

    public function attributes()
    {
        return [
            'title' => '位置名称',
            'type' => '位置标识'
        ];
    }

    /**
     * 验证标识的唯一性
     * @return ValidateBase
     */
    protected function after_validate()
    {
        if (empty($this->error)) {
            if ($this->data['type']) {
                $service = new AdpositionService();
                $expect = $this->type == 'edit' ? [$this->data['id']] : [];
                $exist = $service->exist(['type' => trim($this->data['type'])], $expect);
                if ($exist) {
                    $this->error = '位置标识已存在';
                }
            }
        }
        return parent::after_validate(); // TODO: Change the autogenerated stub
    }
}
