<?php

namespace App\Validates;


use App\Services\ConfigService;

class ConfigValidate extends ValidateBase
{
    public function rules()
    {
        return [
            'title' => 'required|min:2|max:50',
            'type' => 'required|min:3|max:50|alpha_dash',
            'style'=>'required',
            'listsort' => 'integer'
        ];
    }

    public function attributes()
    {
        return [
            'title' => '配置标题',
            'type' => '配置标识',
            'style'=>'配置类型',
            'listsort' => '显示顺序'
        ];
    }
    protected function after_validate()
    {
        if (empty($this->error)) {
            if ($this->data['type']) {
                $service = new ConfigService();
                $expect = $this->type == 'edit' ? [$this->data['id']] : [];
                $exist = $service->exist(['type' => trim($this->data['type'])], $expect);
                if ($exist) {
                    $this->error = '配置标识已存在';
                }
            }
        }
        return parent::after_validate(); // TODO: Change the autogenerated stub
    }
}
