<?php

namespace App\Validates;


use App\Services\DictDataService;

class DictDataValidate extends ValidateBase
{
    public function rules()
    {
        return [
            'name' => 'required|min:2|max:50|alpha_dash',
            'value' => 'required',
            'type' => 'required',
            'listsort' => 'required|integer'
        ];
    }

    public function attributes()
    {
        return [
            'name' => '字典标签',
            'value' => '字典键值',
            'type' => '字典类型',
            'listsort' => '显示顺序'
        ];
    }

    /**
     * 验证数据值的唯一性
     * @return ValidateBase
     */
    protected function after_validate()
    {
        if (empty($this->error)) {
            if ($this->data['type'] && isset($this->data['value'])) {
                $service = new DictDataService();
                $expect = $this->type == 'edit' ? [$this->data['id']] : [];
                $exist = $service->exist(['type' => trim($this->data['type']), 'value' => trim($this->data['value'])], $expect);
                if ($exist) {
                    $this->error = '该字典类型下已存在此键值';
                }
            }
        }
        return parent::after_validate(); // TODO: Change the autogenerated stub
    }
}
