<?php

namespace App\Validates;


class RedtypeValidate extends ValidateBase
{
    public function rules()
    {
        return [
            'title' => 'required|min:2|max:50',
            'type' => 'required'
        ];
    }

    public function attributes()
    {
        return [
            'title' => '跳转名称',
            'type' => '跳转类型'
        ];
    }

    /**
     * 验证必填信息
     * @return ValidateBase
     */
    protected function after_validate()
    {
        if (empty($this->error)) {

        }
        return parent::after_validate(); // TODO: Change the autogenerated stub
    }
}
