<?php
// +----------------------------------------------------------------------
// | B5LaravelCMF
// +----------------------------------------------------------------------
// | Author: 李恒 <357145480@qq.com>
// +----------------------------------------------------------------------
namespace App\Validates;


use App\Services\WebSiteService;

class WebSiteValidate extends ValidateBase
{
    public function rules()
    {
        return [
            'title' => 'required|min:2|max:50',
            'name' => 'required|min:2|max:50',
            'code' => 'required|min:1|max:20|alpha_num'
        ];
    }

    public function attributes()
    {
        return [
            'title' => '站点标题',
            'name' => '站点名称',
            'code' =>'站点标识'
        ];
    }
    /**
     * 验证标识的唯一性
     * @return ValidateBase
     */
    protected function after_validate()
    {
        if (empty($this->error)) {
            if ($this->data['code']) {
                $service = new WebSiteService();
                $expect = $this->type == 'edit' ? [$this->data['id']] : [];
                $exist = $service->exist(['code' => trim($this->data['code'])], $expect);
                if ($exist) {
                    $this->error = '站点标识已存在';
                }
            }
        }
        return parent::after_validate(); // TODO: Change the autogenerated stub
    }
}
