<?php

namespace App\Http\Controllers\Admin;


use App\Services\AdminService;
use App\Services\AuthgroupService;
use Illuminate\Http\Request;

class AdminController extends Backend
{

    /**
     * 构造方法
     * AdminController constructor.
     * @param Request $request
     */
    public function __construct(Request $request)
    {
        parent::__construct($request);
        $this->service = new AdminService();
    }

    public function edit()
    {
        if(!IS_POST){
            $authgroup=(new AuthgroupService())->getSelectList(true);
            view()->share('authgroup',$authgroup);
        }

        return parent::edit(); // TODO: Change the autogenerated stub
    }

}
