<?php

namespace App\Http\Controllers\Admin;

use App\Services\ConfigService;
use Illuminate\Http\Request;

class ConfigController extends Backend
{
    public function __construct(Request $request)
    {
        parent::__construct($request);
        $this->service = new ConfigService();
    }
    public function add()
    {
        if(!IS_POST){
            view()->share('stylelist',$this->service->getStyleList());
        }
        return parent::add(); // TODO: Change the autogenerated stub
    }
    public function edit()
    {
        if(!IS_POST){
            view()->share('stylelist',$this->service->getStyleList());
        }
        return parent::edit(); // TODO: Change the autogenerated stub
    }
}
