<?php

namespace App\Http\Controllers\Admin;


use App\Services\DictDataService;
use App\Services\DictTypeService;
use Illuminate\Http\Request;

class DictdataController extends Backend
{
    public $type_service;
    public function __construct(Request $request)
    {
        parent::__construct($request);
        $this->service = new DictDataService();
        $this->type_service=new DictTypeService();
    }

    public function index()
    {
        if(!IS_POST){
            view()->share('typelist',$this->type_service->getTypeList());
        }
        return parent::index(); // TODO: Change the autogenerated stub
    }
    public function add()
    {
        if(!IS_POST){
            view()->share('typelist',$this->type_service->getTypeList());
        }
        return parent::add(); // TODO: Change the autogenerated stub
    }
    public function edit()
    {
        if(!IS_POST){
            view()->share('typelist',$this->type_service->getTypeList());
        }
        return parent::edit(); // TODO: Change the autogenerated stub
    }
}
