<?php
// +----------------------------------------------------------------------
// | B5LaravelCMF
// +----------------------------------------------------------------------
// | Author: 李恒 <357145480@qq.com>
// +----------------------------------------------------------------------
namespace App\Http\Controllers\Admin;

use App\Services\MapplyService;
use Illuminate\Http\Request;

class MapplyController extends Backend
{
    public function __construct(Request $request)
    {
        parent::__construct($request);
        $this->service = new MapplyService();
    }

    public function add()
    {
        view()->share('fieldList',$this->service->extField());
        return parent::add(); // TODO: Change the autogenerated stub
    }
    public function edit()
    {
        view()->share('fieldList',$this->service->extField());
        return parent::edit(); // TODO: Change the autogenerated stub
    }
}
